M48
; DRILL file {KiCad 9.0.1} date 2025-09-15T21:48:15-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-09-15T21:48:15-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.5496Y-2.3819
X5.5496Y-2.5787
T2
X5.689Y-2.0472
X5.689Y-4.252
M30
