M48
; DRILL file {KiCad 9.0.1} date 2025-09-15T21:48:15-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-09-15T21:48:15-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X5.872Y-2.7618
T2
X5.8323Y-2.3819
X5.8323Y-2.4803
X5.8323Y-2.5787
M30
