M48
; DRILL file {KiCad 9.0.3} date 2025-10-13T20:54:42-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-10-13T20:54:42-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.6559Y-2.5335
T2
X5.689Y-2.0472
X5.689Y-4.252
M30
